### ISSUE TITLE
Mouse Issue

### ISSUE THREAD

**Issue by ghost** [vinodnimbalkar/dotfiles#1]
Hey, I like your nvim config.

I've a little problem, in your config the mouse are totally disabled bt I wanna activate mouse scrolling and clicking, etc,

How can I do that?? I'm new to vim (sorry for my poor English) :(

**Comment by vinodnimbalkar** [comment]
Thanks,
in [settings.lua](https://github.com/vinodnimbalkar/dotfiles/blob/master/.config/nvim/lua/settings.lua) file, you can set
`opt("o", "mouse", "a")                         -- Mouse On`

**Comment by ghost** [comment]
Thank You, problem solved :)
